language: python
python:
  - 3.8

services:
  postgresql
addons:
    postgresql: '9.5'
install:
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest CalculoPECLD --cov=CalculoPECLD
after_success:
  - codecov